version: V1.0.0
name: "huobiService"
mode: "dev"
port: 8887
start_time: "2021-11-01"
machine_id: 1
dataNum: 300
#redis:
#  host: "10.10.10.200"
#  port: 6379
#  password: ""
#  db: 5
#  pool_size: 100
#
#
log:
  level: "error"
  filename: "huobiService.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "10.10.10.200"
  port: 3306
  user: "osx_v3"
  password: "fBfhZjHYE2xCTf2S"
  dbname: "osx_v3"
  mysql_max_open_conns: 20
  mysql_max_idle_conns: 10

#mysql:
#  host: "192.168.175.128"
#  port: 3308
#  user: "root"
#  password: "123456"
#  dbname: "test"
#  mysql_max_open_conns: 20
#  mysql_max_idle_conns: 10

#redis:
#  host: "192.168.186.128"
#  port: 6379
#  password: ""
#  db: 6
#  pool_size: 100

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 6
  pool_size: 100

