version: V1.0.0
name: "huobiService"
mode: "dev"
port: 8887
start_time: "2021-11-01"
machine_id: 1
dataNum: 300
redis:
  host: "10.10.10.200"
  port: 6379
  password: ""
  db: 6
  pool_size: 100


mysql:
  host: "10.10.10.200"
  port: 3306
  user: "osx"
  password: "EYW5M7DECdhyX3d2"
  dbname: "osx"
  mysql_max_open_conns: 20
  mysql_max_idle_conns: 10